// mypages.js
// 2023-3-1

exports.genHomePage = function(data){
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Home Page</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Home Page</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-hoverable">
                        <a href="http://localhost:7777/pessoas">
                            <li>Lista de pessoas</li>
                        </a>
                        <a href="http://localhost:7777/ordDesc">
                            <li>Lista de pessoas ordenada</li>
                        </a>
                        <a href="http://localhost:7777/pessoas/distrSexo">
                            <li>Distribuição por sexo</li>
                        </a>
                        <a href="http://localhost:7777/pessoas/distrDesporto">
                            <li>Distribuição por desporto</li>
                        </a>
                        <a href="http://localhost:7777/pessoas">
                            <li>Top 10 de profissões</li>
                        </a>
                    </ul>
                </div>
                <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `   
    return pagHTML
}

exports.genMainPage = function(lista, data, title = "Lista de Pessoas na Base de Dados"){
    lista.sort()

    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${title} (${lista.length})</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>
    `

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}"> 
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                    </a>
                </tr>
        `
    }
                            
    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div> 
        </body>
    </html>
    `

    return pagHTML;
}

exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${pessoa.nome}</h1>
                </header>

                <div class="w3-container">
    `

    pagHTML += `
    <table class="w3-table-all">
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Idade</th>
            <th>Sexo</th>
            <th>Morada</th>
            <th>Profissão</th>
        </tr>
        <tr>
            <td>${pessoa.id}</td>
            <td>${pessoa.nome}</td>
            <td>${pessoa.idade}</td>
            <td>${pessoa.sexo}</td>
            <td>Cidade: ${pessoa.morada.cidade} | Distrito: ${pessoa.morada.distrito}</td>
            <td>${pessoa.profissao}</td>
        </tr>
    </table>
    `
//     // Automatic way of displaying information about the person
//     pagHTML+= `
//     <table class= "w3-table-all">
//     `
//     for (var key in pessoa) {
//         pagHTML += "<tr>"
//         var value = pessoa[key];
//         if (typeof value == "object"){
//             for (var keyi in value){
//                 pagHTML += `
//                 <td>${keyi}</td>
//                 <td>${value[keyi]}</td>
//                 `
//             }
//         }
//         else{
//             pagHTML += `
//                 <td>${key}</td>
//                 <td>${pessoa[key]}</td>
//                 `
//         }
//         pagHTML+= `
//             </tr>
//         `
//       }

//       pagHTML+= `
//     </table>
//   `

                            
    pagHTML += `
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div> 
        </body>
    </html>
    `

    return pagHTML;
}


exports.genDistrSexo = function(lista, data){
    var sex = {"masculino":0, "feminino":0, "outro":0}
    for (p of lista){
        sex[p.sexo] += 1
    }

    pagHTML = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Distribuição por sexo</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Sexo</th>
                    <th>Frequência</th>
                </tr>
                <tr>
                    <td>Masculino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=masculino">${sex["masculino"]}</a></td>
                </tr>
                <tr>
                    <td>Feminino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=feminino">${sex["feminino"]}</a></td>
                </tr> 
                <tr>
                    <td>Outro</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=outro">${sex["outro"]}</a></td>
                </tr> 
            </table>
            </div>
            <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                <h5>Generated by pessoas-server: ${data}</h5>
            </footer>
        </div>
    </body>
</html>
    
    `
    return pagHTML
}

exports.genDistrDesporto = function(lista, data){
    var desportos = {}
    for (let p of lista){
        for (let d of p.desportos){
            if (d in desportos){
                desportos[d] += 1
            }
            else{
                desportos[d] = 1
            }
        }
    }

    let sortable = [];
    for (var d in desportos) {
        sortable.push([d, desportos[d]]);
    }

    sortable.sort(function(a, b) {
        return b[1] - a[1];
    })

    pagHTML = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Distribuição dos desportos</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Distribuição por sexo</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Desporto</th>
                    <th>Frequência</th>
                </tr>
                `
    for (let s of sortable){
        pagHTML += `
        <tr>
            <td>${s[0]}</td>
            <td><a href="http://localhost:7777/pessoas">${s[1]}</a></td>
        </tr>`

    }
                
                `
            </table>
            </div>
            <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                <h5>Generated by pessoas-server: ${data}</h5>
            </footer>
        </div>
    </body>
</html>
    
    `
    return pagHTML
}