// mypages.js
// 2023-3-1

exports.genHomePage = function(data){
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Home Page</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Home Page</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-hoverable">
                        <a href="http://localhost:7777/pessoas">
                            <li>Lista de pessoas</li>
                        </a>
                        <a href="http://localhost:7777/ordAsc">
                            <li>Lista de pessoas ordenada</li>
                        </a>
                        <a href="http://localhost:7777/pessoas/distrSexo">
                            <li>Distribuição por sexo</li>
                        </a>
                        <a href="http://localhost:7777/pessoas/distrDesporto">
                            <li>Distribuição por desporto</li>
                        </a>
                        <a href="http://localhost:7777/pessoas/profissoes?top=10">
                            <li>Top 10 de profissões</li>
                        </a>
                    </ul>
                </div>
                <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `   
    return pagHTML
}

// Recebe uma lista de pessoas e gera uma página HTML com essas pessoas.
exports.genMainPage = function(lista, data, title = "Lista de Pessoas na Base de Dados"){
    lista.sort()

    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <a href="http://localhost:7777" class="w3-button">Home</a>
                    <h1>${title} (${lista.length})</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>
    `

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}"> 
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                    </a>
                </tr>
        `
    }
                            
    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div> 
        </body>
    </html>
    `

    return pagHTML;
}

exports.genPessoaPage = function(pessoa, data){ 
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>${pessoa.nome}</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                <a href="http://localhost:7777" class="w3-button">Home</a>
                    <h1>${pessoa.nome}</h1>
                </header>
                <div class="w3-container">
                    <ul class="w3-ul w3-border w3-dark-grey">`

    for (var key in pessoa) {
        pagHTML += `
            <li>${key}</li>
        `
        var value = pessoa[key];
        if (typeof value == "object"){
            pagHTML += `
                    <ul class="w3-ul w3-border w3-light-grey">`
            for (var keyi in value){
                if(key == "desportos"){
                    pagHTML += `
                    <a href="http://localhost:7777/pessoas/desporto=${value[keyi]}">
                    <li>${value[keyi]}</li>
                    </a>`
                }
                //else if( key != "atributos" && key != "partido_politico") { // talvez desse pra ter isto melhor feito, se distinguisse objeto de array.
                else if (value instanceof Array) {
                    pagHTML += `
                    <li>${value[keyi]}</li>`
                }
                else{
                    pagHTML += `
                    <li> ${keyi} : ${value[keyi]}</li>`
                }
            }
            pagHTML += `
            </ul>`
        }
        else{
            pagHTML += `
                <ul class="w3-ul w3-border w3-light-grey">
                <li> ${value}</li>
                </ul>`
        }
    }

    pagHTML += `
                </ul>
                </div>
                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML;
}


exports.genDistrSexo = function(lista, data){
    var sex = {"masculino":0, "feminino":0, "outro":0}
    for (p of lista){
        sex[p.sexo] += 1
    }

    var pagHTML = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Distribuição por sexo</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <a href="http://localhost:7777" class="w3-button">Home</a>
                <h1>Distribuição por sexo</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Sexo</th>
                    <th>Frequência</th>
                </tr>
                <tr>
                    <td>Masculino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=masculino">${sex["masculino"]}</a></td>
                </tr>
                <tr>
                    <td>Feminino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=feminino">${sex["feminino"]}</a></td>
                </tr> 
                <tr>
                    <td>Outro</td>
                    <td><a href="http://localhost:7777/pessoas/sexo=outro">${sex["outro"]}</a></td>
                </tr> 
            </table>
            </div>
            <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                <h5>Generated by pessoas-server: ${data}</h5>
            </footer>
        </div>
    </body>
</html>
    
    `
    return pagHTML
}

exports.genDistrDesporto = function(lista, data){
    var desportos = {}
    for (let p of lista){
        for (let d of p.desportos){
            if (d in desportos){
                desportos[d] += 1
            }
            else{
                desportos[d] = 1
            }
        }
    }

    let sorted = [];
    for (var d in desportos) {
        sorted.push([d, desportos[d]]);
    }

    sorted.sort((a, b) => {
        return b[1] - a[1];
    })

    var pagHTML = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Distribuição por desporto</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <a href="http://localhost:7777" class="w3-button">Home</a>
                <h1>Distribuição por desporto</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Desporto</th>
                    <th>Frequência</th>
                </tr>
                `
    for (let s of sorted){
        pagHTML += `
        <tr>
            <td>${s[0]}</td>
            <td><a href="http://localhost:7777/pessoas/desporto=${s[0]}">${s[1]}</a></td>
        </tr>`
    }
                `
            </table>
            </div>
            <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                <h5>Generated by pessoas-server: ${data}</h5>
            </footer>
        </div>
    </body>
</html>
`
    return pagHTML
}

exports.genProfissaoPage = function(topProfissao, top, data){
    var pagHTML = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Top ${top} de profissões</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <a href="http://localhost:7777" class="w3-button">Home</a>
                <h1>Top ${top} de profissões</h1>
            </header>

            <div class="w3-container">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Profissão</th>
                    <th>Frequência</th>
                </tr>`

    for (let p in topProfissao){
        pagHTML += `
        <tr>
            <td>${p}</td>
            <td><a href="http://localhost:7777/pessoas/profissao=${p}">${topProfissao[p]}</a></td>
        </tr>`
    }
`
            </table>
            </div>
            <footer class="w3-container w3-deep-purple w3-bottom w3-center">
                <h5>Generated by pessoas-server: ${data}</h5>
            </footer>
        </div>
    </body>
</html>
    `

    return pagHTML
}